component_depth: 1
languages:
- java
exclude:
- ./build/.*
- ./build/com/.*
- ./build/com/ecyrd/.*
- ./build/com/ecyrd/jspwiki/.*
- ./build/com/ecyrd/jspwiki/attachment/.*
- ./build/com/ecyrd/jspwiki/auth/.*
- ./build/com/ecyrd/jspwiki/auth/acl/.*
- ./build/com/ecyrd/jspwiki/auth/authorize/.*
- ./build/com/ecyrd/jspwiki/auth/login/.*
- ./build/com/ecyrd/jspwiki/auth/permissions/.*
- ./build/com/ecyrd/jspwiki/auth/user/.*
- ./build/com/ecyrd/jspwiki/content/.*
- ./build/com/ecyrd/jspwiki/dav/.*
- ./build/com/ecyrd/jspwiki/dav/items/.*
- ./build/com/ecyrd/jspwiki/dav/methods/.*
- ./build/com/ecyrd/jspwiki/diff/.*
- ./build/com/ecyrd/jspwiki/event/.*
- ./build/com/ecyrd/jspwiki/filters/.*
- ./build/com/ecyrd/jspwiki/forms/.*
- ./build/com/ecyrd/jspwiki/htmltowiki/.*
- ./build/com/ecyrd/jspwiki/i18n/.*
- ./build/com/ecyrd/jspwiki/modules/.*
- ./build/com/ecyrd/jspwiki/parser/.*
- ./build/com/ecyrd/jspwiki/plugin/.*
- ./build/com/ecyrd/jspwiki/preferences/.*
- ./build/com/ecyrd/jspwiki/providers/.*
- ./build/com/ecyrd/jspwiki/render/.*
- ./build/com/ecyrd/jspwiki/rpc/.*
- ./build/com/ecyrd/jspwiki/rpc/atom/.*
- ./build/com/ecyrd/jspwiki/rpc/json/.*
- ./build/com/ecyrd/jspwiki/rss/.*
- ./build/com/ecyrd/jspwiki/search/.*
- ./build/com/ecyrd/jspwiki/tags/.*
- ./build/com/ecyrd/jspwiki/ui/.*
- ./build/com/ecyrd/jspwiki/ui/admin/.*
- ./build/com/ecyrd/jspwiki/ui/admin/beans/.*
- ./build/com/ecyrd/jspwiki/ui/progress/.*
- ./build/com/ecyrd/jspwiki/url/.*
- ./build/com/ecyrd/jspwiki/util/.*
- ./build/com/ecyrd/jspwiki/util/comparators/.*
- ./build/com/ecyrd/jspwiki/workflow/.*
- ./build/com/ecyrd/jspwiki/xmlrpc/.*
- ./build/com/ecyrd/management/.*
- ./build/org/.*
- ./build/org/apache/.*
- ./build/org/apache/catalina/.*
- ./build/org/apache/catalina/util/.*
- ./doc/.*
- ./doc/eclipse/.*
- ./etc/.*
- ./etc/db/.*
- ./etc/db/hsql/.*
- ./etc/db/postgresql/.*
- ./etc/dtd/.*
- ./etc/i18n/.*
- ./etc/i18n/plugin/.*
- ./etc/i18n/templates/.*
- ./etc/ini/.*
- ./lib/.*
- ./tests/.*
- ./tests/build/.*
- ./tests/build/com/.*
- ./tests/build/com/ecyrd/.*
- ./tests/build/com/ecyrd/jspwiki/.*
- ./tests/build/com/ecyrd/jspwiki/attachment/.*
- ./tests/build/com/ecyrd/jspwiki/auth/.*
- ./tests/build/com/ecyrd/jspwiki/auth/acl/.*
- ./tests/build/com/ecyrd/jspwiki/auth/authorize/.*
- ./tests/build/com/ecyrd/jspwiki/auth/login/.*
- ./tests/build/com/ecyrd/jspwiki/auth/permissions/.*
- ./tests/build/com/ecyrd/jspwiki/auth/user/.*
- ./tests/build/com/ecyrd/jspwiki/content/.*
- ./tests/build/com/ecyrd/jspwiki/dav/.*
- ./tests/build/com/ecyrd/jspwiki/diff/.*
- ./tests/build/com/ecyrd/jspwiki/filters/.*
- ./tests/build/com/ecyrd/jspwiki/htmltowiki/.*
- ./tests/build/com/ecyrd/jspwiki/parser/.*
- ./tests/build/com/ecyrd/jspwiki/plugin/.*
- ./tests/build/com/ecyrd/jspwiki/providers/.*
- ./tests/build/com/ecyrd/jspwiki/render/.*
- ./tests/build/com/ecyrd/jspwiki/rss/.*
- ./tests/build/com/ecyrd/jspwiki/search/.*
- ./tests/build/com/ecyrd/jspwiki/ui/.*
- ./tests/build/com/ecyrd/jspwiki/url/.*
- ./tests/build/com/ecyrd/jspwiki/util/.*
- ./tests/build/com/ecyrd/jspwiki/util/comparators/.*
- ./tests/build/com/ecyrd/jspwiki/web/.*
- ./tests/build/com/ecyrd/jspwiki/workflow/.*
- ./tests/build/com/ecyrd/jspwiki/xmlrpc/.*
- ./tests/build/com/foo/.*
- ./tests/build/stress/.*
- ./tests/com/.*
- ./tests/com/ecyrd/.*
- ./tests/com/ecyrd/jspwiki/.*
- ./tests/com/ecyrd/jspwiki/attachment/.*
- ./tests/com/ecyrd/jspwiki/auth/.*
- ./tests/com/ecyrd/jspwiki/auth/acl/.*
- ./tests/com/ecyrd/jspwiki/auth/authorize/.*
- ./tests/com/ecyrd/jspwiki/auth/login/.*
- ./tests/com/ecyrd/jspwiki/auth/permissions/.*
- ./tests/com/ecyrd/jspwiki/auth/user/.*
- ./tests/com/ecyrd/jspwiki/content/.*
- ./tests/com/ecyrd/jspwiki/dav/.*
- ./tests/com/ecyrd/jspwiki/diff/.*
- ./tests/com/ecyrd/jspwiki/filters/.*
- ./tests/com/ecyrd/jspwiki/htmltowiki/.*
- ./tests/com/ecyrd/jspwiki/parser/.*
- ./tests/com/ecyrd/jspwiki/plugin/.*
- ./tests/com/ecyrd/jspwiki/providers/.*
- ./tests/com/ecyrd/jspwiki/render/.*
- ./tests/com/ecyrd/jspwiki/rss/.*
- ./tests/com/ecyrd/jspwiki/search/.*
- ./tests/com/ecyrd/jspwiki/ui/.*
- ./tests/com/ecyrd/jspwiki/url/.*
- ./tests/com/ecyrd/jspwiki/util/.*
- ./tests/com/ecyrd/jspwiki/util/comparators/.*
- ./tests/com/ecyrd/jspwiki/web/.*
- ./tests/com/ecyrd/jspwiki/workflow/.*
- ./tests/com/ecyrd/jspwiki/xmlrpc/.*
- ./tests/com/foo/.*
- ./tests/etc/.*
- ./tests/etc/ini/.*
- ./tests/etc/selenium/.*
- ./tests/etc/selenium/tests/.*
- ./tests/etc/selenium/tests/all/.*
- ./tests/lib/.*
- ./tests/stress/.*
